// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI chatbot that answers questions based on Rahul's resume and LinkedIn data.
 *
 * - aiChatbot - A function that handles the chatbot interaction.
 * - AIChatbotInput - The input type for the aiChatbot function.
 * - AIChatbotOutput - The return type for the aiChatbot function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AIChatbotInputSchema = z.object({
  query: z.string().describe('The user query about Rahul.'),
});
export type AIChatbotInput = z.infer<typeof AIChatbotInputSchema>;

const AIChatbotOutputSchema = z.object({
  response: z.string().describe('The chatbot response to the user query.'),
});
export type AIChatbotOutput = z.infer<typeof AIChatbotOutputSchema>;

export async function aiChatbot(input: AIChatbotInput): Promise<AIChatbotOutput> {
  return aiChatbotFlow(input);
}

const resumeData = `
Rahul Ranjan Pandey
Software Engineer
Experience:
- Google
  - Software Engineer, 2022-Present
- Amazon
  - Software Development Intern, 2021
Education:
- Indian Institute of Technology (IIT), Delhi
  - Bachelor of Technology in Computer Science, 2018-2022
Skills:
- TypeScript
- React
- Next.js
- Firebase
- Genkit
`;

const linkedInData = `
Rahul Ranjan Pandey
Software Engineer at Google
Skills:
- TypeScript
- React
- Next.js
Experience:
- Google, 2022-Present
- Amazon, 2021
Education
- IIT Delhi, 2018-2022
`;

const shouldIncludeResumeInfo = ai.defineTool({
  name: 'shouldIncludeResumeInfo',
  description: 'Decides whether to include resume information in the response.',
  inputSchema: z.object({
    query: z.string().describe('The user query.'),
  }),
  outputSchema: z.boolean().describe('Whether to include resume information.'),
},
async (input) => {
    // Basic logic to determine if resume info should be included.
    // More sophisticated logic could be implemented here.
    return input.query.toLowerCase().includes('experience') || input.query.toLowerCase().includes('education') || input.query.toLowerCase().includes('skills');
  }
);

const shouldIncludeLinkedInInfo = ai.defineTool({
  name: 'shouldIncludeLinkedInInfo',
  description: 'Decides whether to include LinkedIn information in the response.',
  inputSchema: z.object({
    query: z.string().describe('The user query.'),
  }),
  outputSchema: z.boolean().describe('Whether to include LinkedIn information.'),
},
async (input) => {
    // Basic logic to determine if LinkedIn info should be included.
    return input.query.toLowerCase().includes('google') || input.query.toLowerCase().includes('amazon');
  }
);

const aiChatbotPrompt = ai.definePrompt({
  name: 'aiChatbotPrompt',
  tools: [shouldIncludeResumeInfo, shouldIncludeLinkedInInfo],
  input: {schema: AIChatbotInputSchema},
  output: {schema: AIChatbotOutputSchema},
  prompt: `You are Rahul Ranjan Pandey, an AI chatbot providing information about yourself based on your resume and LinkedIn data.  You should only ever respond as if you are Rahul Ranjan Pandey, and never acknowledge that you are an AI unless explicitly asked.

User Query: {{{query}}}

{{#if (shouldIncludeResumeInfo query)}}
Resume Data: {{{resumeData}}}
{{/if}}

{{#if (shouldIncludeLinkedInInfo query)}}
LinkedIn Data: {{{linkedInData}}}
{{/if}}

Response:`, // Handlebars template
});

const aiChatbotFlow = ai.defineFlow(
  {
    name: 'aiChatbotFlow',
    inputSchema: AIChatbotInputSchema,
    outputSchema: AIChatbotOutputSchema,
  },
  async input => {
    const {output} = await aiChatbotPrompt({
      ...input,
      resumeData,
      linkedInData,
    });
    return output!;
  }
);
